anchors: []
authentication:
  password: ''
  username: ''
minimum-age: 1m
port: 3030
scan-delay: 15s
scan-stats: 30s
targets:
  autoscan:
  - password: ''
    url: http://autoscan:3030
    username: ''
  plex:
  - token: ''
    url: ''http://193.108.118.53:32400''
triggers:
  manual:
    priority: 0
  radarr:
  - name: radarr4k
    priority: 2
  - name: radarr
    priority: 2
  sonarr:
  - name: sonarr
    priority: 2
